-- Migration SQL: Synchronize production pages table structure with codebase fields
-- Adds all advanced Hero, Header, Brand, and Responsive columns

ALTER TABLE `pages`
  ADD COLUMN `sort_order` INT DEFAULT 0,
  ADD COLUMN `in_navigation` TINYINT DEFAULT 1,
  ADD COLUMN `hero_title` VARCHAR(255) NULL,
  ADD COLUMN `hero_subtitle` TEXT NULL,
  ADD COLUMN `hero_image` VARCHAR(255) NULL,
  ADD COLUMN `hero_cta1_text` VARCHAR(100) NULL,
  ADD COLUMN `hero_cta1_url` VARCHAR(255) NULL,
  ADD COLUMN `hero_cta2_text` VARCHAR(100) NULL,
  ADD COLUMN `hero_cta2_url` VARCHAR(255) NULL,
  ADD COLUMN `hero_bg_color` VARCHAR(100) NULL,
  ADD COLUMN `hero_effect` VARCHAR(50) DEFAULT 'particles',
  ADD COLUMN `hero_variant` VARCHAR(50) DEFAULT 'hero_split_large_image',
  ADD COLUMN `hero_image_layout` VARCHAR(50) DEFAULT 'right',
  ADD COLUMN `hero_image_size` VARCHAR(50) DEFAULT 'large',
  ADD COLUMN `hero_badge` VARCHAR(255) NULL,
  ADD COLUMN `hero_status` TINYINT DEFAULT 1,
  ADD COLUMN `header_bg_mode` VARCHAR(50) DEFAULT 'glass',
  ADD COLUMN `header_opacity` FLOAT DEFAULT 0.65,
  ADD COLUMN `header_blur` INT DEFAULT 20,
  ADD COLUMN `header_shadow` VARCHAR(50) DEFAULT 'moyen',
  ADD COLUMN `header_contrast_mode` VARCHAR(50) DEFAULT 'default',
  ADD COLUMN `logo_light` VARCHAR(255) NULL,
  ADD COLUMN `logo_dark` VARCHAR(255) NULL,
  ADD COLUMN `logo_size` INT DEFAULT 38,
  ADD COLUMN `hero_layout_mode` VARCHAR(50) DEFAULT 'moyen',
  ADD COLUMN `hero_text_position` VARCHAR(50) DEFAULT 'centre',
  ADD COLUMN `hero_text_alignment` VARCHAR(50) DEFAULT 'center',
  ADD COLUMN `hero_text_width` VARCHAR(50) DEFAULT '100%',
  ADD COLUMN `hero_overlay_opacity` FLOAT DEFAULT 0.45,
  ADD COLUMN `hero_shadow_strength` VARCHAR(50) DEFAULT 'moyen',
  ADD COLUMN `hero_image_mobile` VARCHAR(255) NULL,
  ADD COLUMN `responsive_settings` TEXT NULL;
